M48
; DRILL file {KiCad 9.0.0} date 2025-04-09T10:42:48+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-09T10:42:48+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
%
G90
G05
T2
X155.0Y-93.0
T1
G00X150.6Y-93.25
M15
G01X150.6Y-92.75
M16
G05
M30
